module.exports = {
   index: () => {
      return [
        {
          id: 1,
          titulo: 'Banho',
          preco: 'R$ 30,00',
          categoria: 'Higienização completa',
          autor: 'Higienização completa',
          editora: 'Higienização completa',
          idioma: 'Higienização completa',
          paginas: 'Higienização completa',
          publicacao: 'Higienização completa',
          dimensoes: 'Higienização completa',
          acabamento: 'Higienização completa',
          categoria: 'Higienização completa',
          isbn10: 'Higienização completa',
          isbn20: 'Higienização completa',
          sinopse: 'Higienização completa',
          capa: 'banho',
          imagens: 'banho'
        },
        {
          id: 2,
          titulo: 'Banho',
          preco: 'R$ 30,00',
          categoria: 'Higienização completa',
          autor: 'Higienização completa',
          editora: 'Higienização completa',
          idioma: 'Higienização completa',
          paginas: 'Higienização completa',
          publicacao: 'Higienização completa',
          dimensoes: 'Higienização completa',
          acabamento: 'Higienização completa',
          categoria: 'Higienização completa',
          isbn10: 'Higienização completa',
          isbn20: 'Higienização completa',
          sinopse: 'Higienização completa',
          capa: 'banho',
          imagens: 'banho'
        },
        },
        {
          id: 3,
          titulo: 'Banho',
          preco: 'R$ 30,00',
          categoria: 'Higienização completa',
          autor: 'Higienização completa',
          editora: 'Higienização completa',
          idioma: 'Higienização completa',
          paginas: 'Higienização completa',
          publicacao: 'Higienização completa',
          dimensoes: 'Higienização completa',
          acabamento: 'Higienização completa',
          categoria: 'Higienização completa',
          isbn10: 'Higienização completa',
          isbn20: 'Higienização completa',
          sinopse: 'Higienização completa',
          capa: 'banho',
          imagens: 'banho'
        },
        },
        {
          id: 4,
          titulo: 'Banho',
          preco: 'R$ 30,00',
          categoria: 'Higienização completa',
          autor: 'Higienização completa',
          editora: 'Higienização completa',
          idioma: 'Higienização completa',
          paginas: 'Higienização completa',
          publicacao: 'Higienização completa',
          dimensoes: 'Higienização completa',
          acabamento: 'Higienização completa',
          categoria: 'Higienização completa',
          isbn10: 'Higienização completa',
          isbn20: 'Higienização completa',
          sinopse: 'Higienização completa',
          capa: 'banho',
          imagens: 'banho'
        },
        },
      ]
    }
  }
  